// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/entity_service.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/entity_service.go -destination=./internal/services/mock/entity_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-fp-transaction/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockEntityService is a mock of EntityService interface.
type MockEntityService struct {
	ctrl     *gomock.Controller
	recorder *MockEntityServiceMockRecorder
}

// MockEntityServiceMockRecorder is the mock recorder for MockEntityService.
type MockEntityServiceMockRecorder struct {
	mock *MockEntityService
}

// NewMockEntityService creates a new mock instance.
func NewMockEntityService(ctrl *gomock.Controller) *MockEntityService {
	mock := &MockEntityService{ctrl: ctrl}
	mock.recorder = &MockEntityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityService) EXPECT() *MockEntityServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEntityService) Create(ctx context.Context, req models.CreateEntityIn) (*models.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*models.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEntityServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEntityService)(nil).Create), ctx, req)
}

// GetAll mocks base method.
func (m *MockEntityService) GetAll(ctx context.Context) (*[]models.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].(*[]models.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockEntityServiceMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockEntityService)(nil).GetAll), ctx)
}
