// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/common/transaction_notification/transaction_notification.go
//
// Generated by this command:
//
//	mockgen -source=./internal/common/transaction_notification/transaction_notification.go -destination=./internal/common/transaction_notification/mock/transaction_notification_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "bitbucket.org/Amartha/go-fp-transaction/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionNotificationPublisher is a mock of TransactionNotificationPublisher interface.
type MockTransactionNotificationPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionNotificationPublisherMockRecorder
	isgomock struct{}
}

// MockTransactionNotificationPublisherMockRecorder is the mock recorder for MockTransactionNotificationPublisher.
type MockTransactionNotificationPublisherMockRecorder struct {
	mock *MockTransactionNotificationPublisher
}

// NewMockTransactionNotificationPublisher creates a new mock instance.
func NewMockTransactionNotificationPublisher(ctrl *gomock.Controller) *MockTransactionNotificationPublisher {
	mock := &MockTransactionNotificationPublisher{ctrl: ctrl}
	mock.recorder = &MockTransactionNotificationPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionNotificationPublisher) EXPECT() *MockTransactionNotificationPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockTransactionNotificationPublisher) Publish(ctx context.Context, payload models.TransactionNotificationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockTransactionNotificationPublisherMockRecorder) Publish(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockTransactionNotificationPublisher)(nil).Publish), ctx, payload)
}

// PublishLogBalance mocks base method.
func (m *MockTransactionNotificationPublisher) PublishLogBalance(ctx context.Context, payload models.TransactionNotificationPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishLogBalance", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishLogBalance indicates an expected call of PublishLogBalance.
func (mr *MockTransactionNotificationPublisherMockRecorder) PublishLogBalance(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishLogBalance", reflect.TypeOf((*MockTransactionNotificationPublisher)(nil).PublishLogBalance), ctx, payload)
}
